src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    private $hour;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $level;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $player_1;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=true)
     */
    private $player_2;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=true)
     */
    private $player_3;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=true)
     */
    private $player_4;

    /**
     * @ORM\Column(type="date")
     */
    private $createdDate;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?DateTime
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $date = new DateTime(date("d-m-Y H:i", strtotime($date)));
        $this->date = $date;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(string $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getPlayer1(): ?User
    {
        return $this->player_1;
    }

    public function setPlayer1(?User $player_1): self
    {
        $this->player_1 = $player_1;

        return $this;
    }

    public function getPlayer2(): ?User
    {
        return $this->player_2;
    }

    public function setPlayer2(?User $player_2): self
    {
        $this->player_2 = $player_2;

        return $this;
    }

    public function getPlayer3(): ?User
    {
        return $this->player_3;
    }

    public function setPlayer3(?User $player_3): self
    {
        $this->player_3 = $player_3;

        return $this;
    }

    public function getPlayer4(): ?User
    {
        return $this->player_4;
    }

    public function setPlayer4(?User $player_4): self
    {
        $this->player_4 = $player_4;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->createdDate;
    }

    public function setCreatedDate(\DateTimeInterface $createdDate): self
    {
        $this->createdDate = $createdDate;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get the value of hour
     */
    public function getHour()
    {
        return $this->hour;
    }

    /**
     * Set the value of hour
     *
     * @return  self
     */
    public function setHour($hour)
    {
        $this->hour = $hour;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\Regex;

class EventType extends AbstractType
{
    const EVENT_HOURS = [
        "09:00" => "09:00",
        "09:30" => "09:30",
        "10:00" => "10:00",
        "10:30" => "10:30",
        "11:00" => "11:00",
        "11:30" => "11:30",
        "12:00" => "12:00",
        "12:30" => "12:30",
        "13:00" => "13:00",
        "13:30" => "13:30",
        "14:00" => "14:00",
        "14:30" => "14:30",
        "15:00" => "15:00",
        "15:30" => "15:30",
        "16:00" => "16:00",
        "16:30" => "16:30",
        "17:00" => "17:00",
        "17:30" => "17:30",
        "18:00" => "18:00",
        "18:30" => "18:30",
        "19:00" => "19:00",
        "19:30" => "19:30",
        "20:00" => "20:00",
        "20:30" => "20:30",
        "21:00" => "21:00",
        "21:30" => "21:30",
        "22:00" => "22:00",
    ];

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date', TextType::class, [
                'label' => 'Fecha',
                'required' => true,
                'attr' => [
                    'placeholder' => 'dd-mm-yyyy',
                    'type' => 'date',
                ]
            ])
            ->add('hour', ChoiceType::class, [
                'label' => 'Hora',
                'required' => true,
                'choices' => self::EVENT_HOURS,
                'placeholder' => 'Selecciona...',

            ])
            ->add('level', ChoiceType::class, [
                'label' => 'Nivel',
                'required' => true,
                'choices' => [
                    'Iniciación' => 'Iniciación',
                    'Intermedio' => 'Intermedio',
                    'Avanzado' => 'Avanzado'
                ],
                'placeholder' => 'Selecciona...',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Entity\User;
use App\Form\EventType;
use App\Repository\EventRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Date;

/**
 * @Route("/event")
 */

class EventController extends AbstractController
{
    /**
     * @Route("/", name="event_index", methods={"GET"})
     */
    public function index(EventRepository $eventRepository): Response
    {
        $today = new DateTime("NOW");
        $today = $today->format('Y-m-d H:i');
        $events = $eventRepository->getEvents($today);
        $event = new Event();
        $form = $this->createForm(EventType::class, $event, [
            'action' => $this->generateUrl('event_new')
        ]);
        return $this->render('event/index.html.twig', [
            'events' => $events,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/new", name="event_new", methods={"GET","POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $createdDate = new DateTime("NOW");
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);


        $response = [];
        $user = $this->getUser();
        if ($form->isSubmitted() && $form->isValid()) {
            $date = $form['date']->getData() . " " . $form['hour']->getData();
            $event->setCreatedDate($createdDate);
            $event->setDate($date);
            $event->setPlayer1($user);
            $event->setUser($user);
            try {
                $entityManager->persist($event);
                $entityManager->flush();
            } catch (\Exception $e) {
                $response['success'] = false;
                $response['error'] = $e->getMessage();
                $response['message'] = 'Error al crear el partido';
                return new JsonResponse($response);
            }
            $response['success'] = true;
            $response['message'] = '¡Partido creado correctamente!';
        }
        $response = new JsonResponse($response);
        return $this->redirectToRoute('event_index');
    }

    /**
     * @Route("/join-event", name="event_join", options={"expose"=true}, methods={"POST"},)
     */
    public function joinEvent(Request $request, EntityManagerInterface $entityManager, EventRepository $eventRepository): JsonResponse
    {

        if ($request->isXmlHttpRequest()) {
            $user = $this->getUser();
            $eventId = $request->get('eventId');
            // TODO: Recoger que en que posicion de jugador se inscribe
            // $playerNumber = $request->get('playerNumber');

            $userLogedSignedInEvent = $eventRepository->checkIfPlayerIsInEvent($eventId, $user->getId());
            if (!$userLogedSignedInEvent) {
                $event = $eventRepository->find($eventId);
                $event->setPlayer2($user);
                $entityManager->flush();
                $response = [
                    'success' => true,
                    'message' => '¡Inscripción al partido realizada!'
                ];
                return new JsonResponse($response);
            } else {
                $response = [
                    'success' => false,
                    'message' => '¡Ya estas inscrito en el partido, no puedes volver a inscribirte!'
                ];
                return new JsonResponse($response);
            }
        }
        $response = [
            'success' => false,
            'message' => '¡Error al inscribirte en el partido!'
        ];
        return new JsonResponse($response);
    }

    /**
     * @Route("/exit-event", name="event_exit", options={"expose"=true}, methods={"POST"},)
     */
    public function exitEvent(Request $request, EntityManagerInterface $entityManager, EventRepository $eventRepository): JsonResponse
    {

        if ($request->isXmlHttpRequest()) {
            $eventId = $request->get('eventId');
            $playerNumber = $request->get('playerPosition');
            // TODO: Verificar si el jugador q
            $userLogedSignedInEvent = $eventRepository->checkIfPlayerIsInEvent($eventId, $user->getId());
            if (!$userLogedSignedInEvent) {
                $event = $eventRepository->find($eventId);
                $event->setPlayer2(NULL);
                $entityManager->flush();
                $response = [
                    'success' => true,
                    'message' => '¡Inscripción al partido realizada!'
                ];
                return new JsonResponse($response);
            } else {
                $response = [
                    'success' => false,
                    'message' => '¡Ya estas inscrito en el partido, no puedes volver a inscribirte!'
                ];
                return new JsonResponse($response);
            }
        }
        $response = [
            'success' => false,
            'message' => '¡Error al inscribirte en el partido!'
        ];
        return new JsonResponse($response);
    }
}

templates/event/_new_event.html.twig
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#modelId">
    Crear Partido
</button>
<!-- Modal -->
<div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        {{ form_start(form,{'attr': {'id': 'create-event-form'}})}}
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Crear Partido</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-primary" role="alert">
                    <p>Recuerda que es <span class="font-weight-bold">imprescindible que tengas pista reservada</span>
                        para poder jugar el partido.</p>
                </div>
                <div class="container-fluid">
                    {{ form_row(form.date,  {'id': 'datepicker'} ) }}
                    {{ form_row(form.hour) }}
                    {{ form_row(form.level) }}

                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="submit" id="btn-create-event" class="btn btn-success">Crear</button>
            </div>
        </div>
        {{ form_end(form)}}
    </div>
</div>

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Urban Padel - Partidos
{% endblock %}

{% block stylesheets %}
{{ parent() }}
<link rel="stylesheet" href="{{asset('css/event.css')}}">
<link rel="stylesheet" href="{{asset('libs/bootstrap-datepicker/css/bootstrap-datepicker.min.css')}}"></script>

</link>{% endblock %}{% block body %}
{% include "header.html.twig" %}
<div class="container-fluid my-5">
	<div class="d-flex align-items-end flex-column mb-5">
		{% include "event/_new_event.html.twig" %}
	</div>
	<div class="row">
		{% for event in events %}
		<div class="col-sm-12 col-md-12 col-lg-6 col-xl-12 mb-5">
			<div class="card">
				<div class="card-header text-muted">{{event.date|date("d-m-Y H:i")}}</div>
				<div class="card-body text-center">
					<div class="row">
						<div class="col-3 d-flex justify-content-center my-2">
							<div class="d-flex rounded-circle player justify-content-center align-items-center">
								{% if event.player1 %}
								<span>{{event.player1.name}}</span>
								{% else %}
								<i class="fas fa-plus-circle 7x"></i>
								{% endif %}
							</div>
						</div>
						<div class="col-3 d-flex justify-content-center border-right my-2">
							<div class="d-flex rounded-circle player justify-content-center align-items-center clickable" id="player_2"
								{% if event.player2 != true %} onclick="joinEvent({{event.id}})" {% endif %}
								{% if app.user == event.player2 %} onclick="exitFromEvent({{event.id}})"  {% endif %}>
								{% if event.player2 %}
								<span>{{event.player2.name}}</span>
								{% else %}
								<i class="fas fa-plus-circle 7x"></i>
								{% endif %}
							</div>
						</div>
						<div class="col-3 d-flex justify-content-center my-2">
							<div class="d-flex rounded-circle player justify-content-center align-items-center clickable" id="player_3"
								{% if event.player3 != true %} onclick="joinEvent({{event.id}})" {% endif %} 
								{% if app.user == event.player3 %} onclick="exitFromEvent({{event.id}})" {% endif %}>
								{% if event.player3 %}
								<span>{{event.player3.name}}</span>
								{% else %}
								<i class="fas fa-plus-circle 7x"></i>
								{% endif %}
							</div>
						</div>
						<div class="col-3 d-flex justify-content-center my-2">
							<div class="d-flex rounded-circle player justify-content-center align-items-center clickable" id="player_4"
								{% if event.player4 != true %} onclick="joinEvent({{event.id}})" {% endif %} 
								{% if app.user == event.player4 %} onclick="exitFromEvent({{event.id}})" {% endif %} >
								{% if event.player4 %}
								<span>{{event.player4.name}}</span>
								{% else %}
								<i class="fas fa-plus-circle 7x"></i>
								{% endif %}
							</div>
						</div>
					</div>
				</div>
				<div class="card-footer text-muted text-left p-0">
					<div class="row mx-0 align-items-center">
						<div class="col-8 p-2">{{event.User.address}}</div>
						<div class="col-4 border-left">Nivel:
							{{event.level}}</div>
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>

{% endblock %}

{% block javascripts %}
{{ parent() }}
<script src="{{asset('bundles/fosjsrouting/js/router.js')}}"></script>
<script src="{{path('fos_js_routing_js', { callback: 'fos.Router.setData' })}}"></script>
<script src="{{asset('libs/sweetalert/sweetalert.min.js')}}"></script>
<script src="{{asset('libs/bootstrap-datepicker/js/bootstrap-datepicker.js')}}"></script>
<script src="{{asset('libs/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js')}}"></script>
<script src="{{asset('js/app.js')}}"></script>
{% endblock  %}